/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DndRouteRouteImport } from "./routes/dnd/route";
import { Route as GamesRouteImport } from "./routes/games";
import { Route as DndIndexRouteImport } from "./routes/dnd/index";
import { Route as DndCharacterIdRouteImport } from "./routes/dnd/$characterId";
import { Route as DndCreateRouteImport } from "./routes/dnd/create";
import { Route as DndHomebrewIndexRouteImport } from "./routes/dnd/homebrew/index";
import { Route as DndHomebrewTypeIndexRouteImport } from "./routes/dnd/homebrew/$type.$index";
import { Route as DndHomebrewNewTypeRouteImport } from "./routes/dnd/homebrew/new.$type";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DndRouteRoute = DndRouteRouteImport.update({
  id: "/dnd",
  path: "/dnd",
  getParentRoute: () => rootRouteImport,
} as any);
const GamesRoute = GamesRouteImport.update({
  id: "/games",
  path: "/games",
  getParentRoute: () => rootRouteImport,
} as any);
const DndIndexRoute = DndIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DndRouteRoute,
} as any);
const DndCharacterIdRoute = DndCharacterIdRouteImport.update({
  id: "/$characterId",
  path: "/$characterId",
  getParentRoute: () => DndRouteRoute,
} as any);
const DndCreateRoute = DndCreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => DndRouteRoute,
} as any);
const DndHomebrewIndexRoute = DndHomebrewIndexRouteImport.update({
  id: "/homebrew/",
  path: "/homebrew/",
  getParentRoute: () => DndRouteRoute,
} as any);
const DndHomebrewTypeIndexRoute = DndHomebrewTypeIndexRouteImport.update({
  id: "/homebrew/$type/$index",
  path: "/homebrew/$type/$index",
  getParentRoute: () => DndRouteRoute,
} as any);
const DndHomebrewNewTypeRoute = DndHomebrewNewTypeRouteImport.update({
  id: "/homebrew/new/$type",
  path: "/homebrew/new/$type",
  getParentRoute: () => DndRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dnd": typeof DndRouteRouteWithChildren;
  "/games": typeof GamesRoute;
  "/dnd/$characterId": typeof DndCharacterIdRoute;
  "/dnd/create": typeof DndCreateRoute;
  "/dnd/": typeof DndIndexRoute;
  "/dnd/homebrew/": typeof DndHomebrewIndexRoute;
  "/dnd/homebrew/$type/$index": typeof DndHomebrewTypeIndexRoute;
  "/dnd/homebrew/new/$type": typeof DndHomebrewNewTypeRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/games": typeof GamesRoute;
  "/dnd/$characterId": typeof DndCharacterIdRoute;
  "/dnd/create": typeof DndCreateRoute;
  "/dnd": typeof DndIndexRoute;
  "/dnd/homebrew": typeof DndHomebrewIndexRoute;
  "/dnd/homebrew/$type/$index": typeof DndHomebrewTypeIndexRoute;
  "/dnd/homebrew/new/$type": typeof DndHomebrewNewTypeRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dnd": typeof DndRouteRouteWithChildren;
  "/games": typeof GamesRoute;
  "/dnd/$characterId": typeof DndCharacterIdRoute;
  "/dnd/create": typeof DndCreateRoute;
  "/dnd/": typeof DndIndexRoute;
  "/dnd/homebrew/": typeof DndHomebrewIndexRoute;
  "/dnd/homebrew/$type/$index": typeof DndHomebrewTypeIndexRoute;
  "/dnd/homebrew/new/$type": typeof DndHomebrewNewTypeRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dnd"
    | "/games"
    | "/dnd/$characterId"
    | "/dnd/create"
    | "/dnd/"
    | "/dnd/homebrew/"
    | "/dnd/homebrew/$type/$index"
    | "/dnd/homebrew/new/$type";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/games"
    | "/dnd/$characterId"
    | "/dnd/create"
    | "/dnd"
    | "/dnd/homebrew"
    | "/dnd/homebrew/$type/$index"
    | "/dnd/homebrew/new/$type";
  id:
    | "__root__"
    | "/"
    | "/dnd"
    | "/games"
    | "/dnd/$characterId"
    | "/dnd/create"
    | "/dnd/"
    | "/dnd/homebrew/"
    | "/dnd/homebrew/$type/$index"
    | "/dnd/homebrew/new/$type";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DndRouteRoute: typeof DndRouteRouteWithChildren;
  GamesRoute: typeof GamesRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dnd": {
      id: "/dnd";
      path: "/dnd";
      fullPath: "/dnd";
      preLoaderRoute: typeof DndRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/games": {
      id: "/games";
      path: "/games";
      fullPath: "/games";
      preLoaderRoute: typeof GamesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dnd/": {
      id: "/dnd/";
      path: "/";
      fullPath: "/dnd/";
      preLoaderRoute: typeof DndIndexRouteImport;
      parentRoute: typeof DndRouteRoute;
    };
    "/dnd/$characterId": {
      id: "/dnd/$characterId";
      path: "/$characterId";
      fullPath: "/dnd/$characterId";
      preLoaderRoute: typeof DndCharacterIdRouteImport;
      parentRoute: typeof DndRouteRoute;
    };
    "/dnd/create": {
      id: "/dnd/create";
      path: "/create";
      fullPath: "/dnd/create";
      preLoaderRoute: typeof DndCreateRouteImport;
      parentRoute: typeof DndRouteRoute;
    };
    "/dnd/homebrew/": {
      id: "/dnd/homebrew/";
      path: "/homebrew";
      fullPath: "/dnd/homebrew/";
      preLoaderRoute: typeof DndHomebrewIndexRouteImport;
      parentRoute: typeof DndRouteRoute;
    };
    "/dnd/homebrew/$type/$index": {
      id: "/dnd/homebrew/$type/$index";
      path: "/homebrew/$type/$index";
      fullPath: "/dnd/homebrew/$type/$index";
      preLoaderRoute: typeof DndHomebrewTypeIndexRouteImport;
      parentRoute: typeof DndRouteRoute;
    };
    "/dnd/homebrew/new/$type": {
      id: "/dnd/homebrew/new/$type";
      path: "/homebrew/new/$type";
      fullPath: "/dnd/homebrew/new/$type";
      preLoaderRoute: typeof DndHomebrewNewTypeRouteImport;
      parentRoute: typeof DndRouteRoute;
    };
  }
}

interface DndRouteRouteChildren {
  DndCharacterIdRoute: typeof DndCharacterIdRoute;
  DndCreateRoute: typeof DndCreateRoute;
  DndIndexRoute: typeof DndIndexRoute;
  DndHomebrewIndexRoute: typeof DndHomebrewIndexRoute;
  DndHomebrewTypeIndexRoute: typeof DndHomebrewTypeIndexRoute;
  DndHomebrewNewTypeRoute: typeof DndHomebrewNewTypeRoute;
}

const DndRouteRouteChildren: DndRouteRouteChildren = {
  DndCharacterIdRoute: DndCharacterIdRoute,
  DndCreateRoute: DndCreateRoute,
  DndIndexRoute: DndIndexRoute,
  DndHomebrewIndexRoute: DndHomebrewIndexRoute,
  DndHomebrewTypeIndexRoute: DndHomebrewTypeIndexRoute,
  DndHomebrewNewTypeRoute: DndHomebrewNewTypeRoute,
};

const DndRouteRouteWithChildren = DndRouteRoute._addFileChildren(
  DndRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DndRouteRoute: DndRouteRouteWithChildren,
  GamesRoute: GamesRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
